---
- hosts: all
  vars:
    - username: Name
    - access: grant
  tasks:
    - name: multiline shell command
      shell: sh ssh_access_control.sh {{ access }} {{ username }}
      register: stdout

    - name: debug output
      debug: msg={{ stdout }}